name: IQonomy-RDP-ZeroTier

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin "B9o6P2M0" /add
          net localgroup administrators runneradmin /add

      - name: Install ZeroTier
        shell: powershell
        run: |
          $msiPath = "$($env:TEMP)\ZeroTierOne.msi"
          Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile $msiPath
          Start-Process msiexec.exe -ArgumentList "/i", $msiPath, "/qn" -Wait
          
      - name: Join Network
        shell: powershell
        run: |
          # استبدل الـ ID ده بـ Network ID الخاص بك من موقع zerotier.com
          $networkId = "633e31d8a2e99f6f" 
          cd "C:\Program Files (x86)\ZeroTier\One"
          .\zerotier-one_x64.exe -q join $networkId
          Start-Sleep -Seconds 20

      - name: Keep Alive
        run: Start-Sleep -Seconds 21600
